generator: random.Random(20260923).shuffle, 3 draws
orders:
  order0:
  - iron_13
  - iron_04
  - stone_04
  - stone_08
  - wooden_07
  - gold_02
  - iron_01
  - stone_06
  - gold_01
  - stone_09
  - stone_00
  - iron_07
  - diamond_06
  - iron_09
  - wooden_06
  - armor_01
  - stone_07
  - diamond_02
  - armor_12
  - armor_09
  - wooden_04
  - wooden_08
  - redstone_04
  - armor_02
  - iron_15
  - wooden_10
  - iron_06
  - diamond_00
  - iron_11
  - redstone_02
  - iron_08
  - stone_05
  - wooden_09
  - iron_05
  - gold_03
  - armor_07
  - iron_03
  - redstone_05
  - stone_01
  - wooden_00
  - redstone_01
  - iron_02
  - iron_14
  - armor_04
  - stone_03
  - iron_00
  - diamond_05
  - wooden_05
  - gold_06
  - gold_05
  - armor_08
  - wooden_03
  - armor_10
  - armor_00
  - armor_05
  - armor_03
  - diamond_04
  - iron_12
  - wooden_02
  - gold_04
  - diamond_01
  - wooden_01
  - stone_02
  - armor_06
  - diamond_03
  - armor_11
  - redstone_03
  - gold_00
  - iron_10
  - redstone_00
  order1:
  - gold_02
  - stone_02
  - diamond_05
  - gold_03
  - wooden_09
  - armor_01
  - wooden_10
  - gold_05
  - armor_04
  - iron_05
  - redstone_03
  - diamond_00
  - iron_01
  - stone_08
  - redstone_04
  - stone_01
  - diamond_03
  - armor_12
  - iron_00
  - armor_06
  - iron_10
  - stone_00
  - stone_09
  - stone_04
  - redstone_05
  - wooden_08
  - iron_03
  - gold_01
  - stone_03
  - wooden_05
  - iron_07
  - armor_05
  - armor_00
  - iron_04
  - iron_02
  - armor_08
  - iron_08
  - diamond_06
  - stone_07
  - stone_06
  - wooden_07
  - wooden_00
  - redstone_01
  - wooden_04
  - redstone_00
  - iron_12
  - wooden_02
  - iron_13
  - iron_14
  - wooden_06
  - armor_02
  - armor_03
  - armor_07
  - diamond_01
  - stone_05
  - gold_06
  - redstone_02
  - armor_10
  - iron_09
  - diamond_02
  - armor_09
  - armor_11
  - diamond_04
  - wooden_01
  - iron_06
  - iron_15
  - gold_00
  - wooden_03
  - gold_04
  - iron_11
  order2:
  - stone_01
  - wooden_03
  - diamond_04
  - redstone_05
  - redstone_02
  - gold_04
  - iron_13
  - iron_00
  - armor_03
  - wooden_05
  - stone_05
  - gold_05
  - wooden_08
  - armor_01
  - gold_02
  - armor_05
  - gold_01
  - iron_09
  - gold_06
  - armor_10
  - iron_12
  - iron_07
  - iron_02
  - diamond_02
  - armor_06
  - armor_08
  - diamond_01
  - diamond_06
  - wooden_00
  - stone_06
  - wooden_02
  - armor_04
  - redstone_04
  - stone_09
  - iron_03
  - armor_00
  - iron_05
  - redstone_01
  - stone_08
  - wooden_01
  - gold_03
  - armor_11
  - stone_03
  - armor_09
  - iron_11
  - stone_02
  - iron_04
  - wooden_07
  - redstone_03
  - wooden_06
  - iron_06
  - stone_07
  - wooden_10
  - diamond_05
  - iron_10
  - stone_04
  - iron_14
  - iron_15
  - diamond_00
  - wooden_04
  - iron_01
  - diamond_03
  - wooden_09
  - iron_08
  - gold_00
  - armor_12
  - armor_02
  - redstone_00
  - stone_00
  - armor_07
